import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Import and configure Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"], // you can adjust weights as needed
});

export const metadata: Metadata = {
  title: "Urban Cruise Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body className={`${poppins.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
